version: "2.1"
services:
  opbeans-python:
    image: opbeans/opbeans-python:latest
    ports:
      - "127.0.0.1:${OPBEANS_PYTHON_PORT:-8000}:3000"
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    environment:
      - ELASTIC_APM_SERVICE_NAME=${ELASTIC_APM_SERVICE_NAME:-opbeans-python}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL:-http://apm-server:8200}
      - ELASTIC_APM_JS_SERVER_URL=${ELASTIC_APM_JS_SERVER_URL:-http://localhost:8200}
      - ELASTIC_APM_FLUSH_INTERVAL=5
      - ELASTIC_APM_TRANSACTION_MAX_SPANS=50
      - ELASTIC_APM_TRANSACTION_SAMPLE_RATE=0.5
      - ELASTIC_APM_SOURCE_LINES_ERROR_APP_FRAMES
      - ELASTIC_APM_SOURCE_LINES_SPAN_APP_FRAMES=5
      - ELASTIC_APM_SOURCE_LINES_ERROR_LIBRARY_FRAMES
      - ELASTIC_APM_SOURCE_LINES_SPAN_LIBRARY_FRAMES
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=${ELASTIC_CLOUD_URL}
    depends_on:
      redis:
        condition: service_healthy
      apm-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://opbeans-python:8000/"]
      interval: 10s
      retries: 10

  apm-server:
    image: docker.elastic.co/apm/apm-server:${STACK_VERSION:-6.3.0}
    ports:
      - "127.0.0.1:${APM_SERVER_PORT:-8200}:8200"
      - "127.0.0.1:${APM_SERVER_MONITOR_PORT:-6060}:6060"
    command: >
      apm-server -e
        -E apm-server.frontend.enabled=true
        -E apm-server.frontend.rate_limit=100000
        -E apm-server.host=0.0.0.0:8200
        -E apm-server.read_timeout=1m
        -E apm-server.shutdown_timeout=2m
        -E apm-server.write_timeout=1m
        -E setup.template.settings.index.number_of_replicas=0
        -E cloud.id=${ELASTIC_CLOUD_ID}
        -E cloud.auth=${ELASTIC_CLOUD_CREDENTIALS}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    healthcheck:
      test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://apm-server:8200/healthcheck"]
      retries: 10
      interval: 10s

  redis:
    image: redis:4
    ports:
      - 6379:6379
    logging:
      driver: 'json-file'
      options:
          max-size: '2m'
          max-file: '5'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s

volumes:
  esdata:
    driver: local
