---
# Creates a new GitHub release if the version in requirements.txt changed in the main branch and
# if the tag does not exist yet.
name: create-tag

on:
  push:
    branches:
      - main
    paths:
      - requirements.txt

permissions:
  contents: read

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # also fetch tags

      - run: make create-release
        env:
          GH_TOKEN: ${{ secrets.CREATE_TAG_TOKEN }}
